rest_command:
  zapisz_cwu:
    url: "http://192.168.100.126/save.php"
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    payload: >
      data=[{"name":"val9","value":"{{ '1' if is_state('input_select.tryb_cwu', 'ZAL') else '0' }}"},
            {"name":"val15","value":"0"},
            {"name":"val25","value":"1"}]

  ustaw_temp_cwu:
    url: "http://192.168.100.126/save.php"
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    payload: >
      data=[{"name":"val40023","value":"{{ states('input_number.temp_cwu_on') | replace('.', ',') }}"},
            {"name":"val40024","value":"{{ states('input_number.temp_cwu_off') | replace('.', ',') }}"}]

  zapisz_tryb_ogrzewania:
    url: "http://192.168.100.126/save.php"
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    payload: >
      data=[{"name":"val10","value":"{{ '1' if is_state('input_select.tryb_ogrzewania', 'OGRZEWANIE') else '0' }}"}]

  zapisz_temp_pomieszczenia:
    url: "http://192.168.100.126/save.php"
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    payload: >
      data=[{"name":"val40006","value":"{{ states('input_number.temp_pomieszczenia') | round(2) | string | replace('.', ',') }}"}]

  zapisz_antylegionella:
    url: "http://192.168.100.126/save.php"
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    payload: >
      data=[{"name":"val25","value":"{{ '1' if is_state('input_select.antylegionella', 'ZAL') else '0' }}"}]

input_number:
  temp_cwu_on:
    name: Temperatura załączenia CWU
    min: 30
    max: 60
    step: 0.5
    unit_of_measurement: "°C"
    mode: box
    initial: 43

  temp_cwu_off:
    name: Temperatura wyłączenia CWU
    min: 30
    max: 70
    step: 0.5
    unit_of_measurement: "°C"
    mode: box
    initial: 48

  temp_pomieszczenia:
    name: Temperatura pomieszczenia
    min: 10
    max: 30
    step: 0.1
    unit_of_measurement: "°C"
    mode: box
    initial: 18.5





input_select:
  tryb_cwu:
    name: Tryb CWU
    options:
      - WYL
      - ZAL
    initial: WYL

  tryb_ogrzewania:
    name: Tryb ogrzewania
    options:
      - WYŁ.
      - OGRZEWANIE
    initial: WYŁ.


  antylegionella:
    name: Antylegionella
    options:
      - WYL
      - ZAL
    initial: WYL

# Stiebel Eltron
sensor:
  - platform: rest
    name: "Temperatura zasobnika na dole Stiebel Eltron"
    resource: http://192.168.100.126/?s=2,7
    method: GET
    # Usunięto nagłówek Cookie
    value_template: >
      {{ value.split('Temperatura zasobnika na dole</td>')[1]
              .split('<td class="value">')[1]
              .split('</td>')[0]
              .replace('°C', '')
              .replace(',', '.') | float }}
    unit_of_measurement: "°C"

  - platform: rest
    name: "Temperatura rury wylotowej Stiebel Eltron"
    resource: http://192.168.100.126/?s=1,0
    method: GET
    # Usunięto nagłówek Cookie
    value_template: >
      {{ value.split('Temp. rury wylotowej</td>')[1]
              .split('<td class="value">')[1]
              .split('</td>')[0]
              .replace('°C', '')
              .replace(',', '.') | float }}
    unit_of_measurement: "°C"

  - platform: rest
    name: "Temperatura wlotu skraplacza Stiebel Eltron"
    resource: http://192.168.100.126/?s=1,0
    method: GET
    # Usunięto nagłówek Cookie
    value_template: >
      {{ value.split('Temp. wlotu skraplacza</td>')[1]
              .split('<td class="value">')[1]
              .split('</td>')[0]
              .replace('°C', '')
              .replace(',', '.') | float }}
    unit_of_measurement: "°C"

  - platform: rest
    name: "Temperatura wylotu skraplacza Stiebel Eltron"
    resource: http://192.168.100.126/?s=1,0
    method: GET
    # Usunięto nagłówek Cookie
    value_template: >
      {{ value.split('Temp. wylotu skraplacza</td>')[1]
              .split('<td class="value">')[1]
              .split('</td>')[0]
              .replace('°C', '')
              .replace(',', '.') | float }}
    unit_of_measurement: "°C"

  - platform: rest
    name: "Temperatura wlotu solanki Stiebel Eltron"
    resource: http://192.168.100.126/?s=1,0
    method: GET
    # Usunięto nagłówek Cookie
    value_template: >
      {{ value.split('Temp. wlotu solanki</td>')[1]
              .split('<td class="value">')[1]
              .split('</td>')[0]
              .replace('°C', '')
              .replace(',', '.') | float }}
    unit_of_measurement: "°C"

  - platform: rest
    name: "Temperatura wylotu solanki Stiebel Eltron"
    resource: http://192.168.100.126/?s=1,0
    method: GET
    # Usunięto nagłówek Cookie
    value_template: >
      {{ value.split('Temp. wylotu solanki</td>')[1]
              .split('<td class="value">')[1]
              .split('</td>')[0]
              .replace('°C', '')
              .replace(',', '.') | float }}
    unit_of_measurement: "°C"

  - platform: rest
    name: "Temperatura zewnętrzna Stiebel Eltron"
    resource: http://192.168.100.126/?s=1,0
    method: GET
    # Usunięto nagłówek Cookie
    value_template: >
      {{ value.split('Temperatura zewnętrzna</td>')[1]
              .split('<td class="value">')[1]
              .split('</td>')[0]
              .replace('°C', '')
              .replace(',', '.') | float }}
    unit_of_measurement: "°C"

  - platform: rest
    name: "Temperatura pomieszczenia Stiebel Eltron"
    resource: http://192.168.100.126/?s=1,0
    method: GET
    # Usunięto nagłówek Cookie
    value_template: >
      {{ value.split('Temp. pomieszczenia</td>')[1]
              .split('<td class="value">')[1]
              .split('</td>')[0]
              .replace('°C', '')
              .replace(',', '.') | float }}
    unit_of_measurement: "°C"

  - platform: rest
    name: "Temperatura skraplacza (manometryczna) Stiebel Eltron"
    resource: http://192.168.100.126/?s=1,0
    method: GET
    # Usunięto nagłówek Cookie
    value_template: >
      {{ value.split('Temp. skraplacza (manometryczna)</td>')[1]
              .split('<td class="value">')[1]
              .split('</td>')[0]
              .replace('°C', '')
              .replace(',', '.') | float }}
    unit_of_measurement: "°C"

  - platform: rest
    name: "Temperatura przegrzania Stiebel Eltron"
    resource: http://192.168.100.126/?s=1,0
    method: GET
    # Usunięto nagłówek Cookie
    value_template: >
      {{ value.split('Temp. przegrzania</td>')[1]
              .split('<td class="value">')[1]
              .split('</td>')[0]
              .replace('K', '')
              .replace(',', '.') | float }}
    unit_of_measurement: "K"

  - platform: rest
    name: "Temperatura wychłodzenia Stiebel Eltron"
    resource: http://192.168.100.126/?s=1,0
    method: GET
    # Usunięto nagłówek Cookie
    value_template: >
      {{ value.split('Temp. wychłodzenia</td>')[1]
              .split('<td class="value">')[1]
              .split('</td>')[0]
              .replace('K', '')
              .replace(',', '.') | float }}
    unit_of_measurement: "K"


  - platform: rest
    name: "Prędkość obr. sprężarki Stiebel Eltron"
    resource: http://192.168.100.126/?s=1,0
    method: GET
    # Usunięto nagłówek Cookie
    value_template: >
      {{ value.split('Procentowa prędkość obr. sprężarki</td>')[1]
              .split('<td class="value">')[1]
              .split('</td>')[0]
              .replace('%', '')
              .replace(',', '.') | float }}
    unit_of_measurement: "%"

  - platform: rest
    name: "Stopnie sprężarki Stiebel Eltron"
    resource: http://192.168.100.126/?s=1,0
    method: GET
    # Usunięto nagłówek Cookie
    value_template: >
      {{ value.split('Dostępnie stopnie sprężarki</td>')[1]
              .split('<td class="value">')[1]
              .split('</td>')[0]
              .replace('gear', '')
              .replace(',', '.') | float }}
    unit_of_measurement: "gear"

  - platform: rest
    name: "Zawór mieszający ZOD Stiebel Eltron"
    resource: http://192.168.100.126/?s=1,0
    method: GET
    # Usunięto nagłówek Cookie
    value_template: >
      {{ value.split('Sygnał ster. zaworu mieszającego ZOD</td>')[1]
              .split('<td class="value">')[1]
              .split('</td>')[0]
              .replace('%', '')
              .replace(',', '.') | float }}
    unit_of_measurement: "%"

  - platform: rest
    name: "Prędkość pompy solanki Stiebel Eltron"
    resource: http://192.168.100.126/?s=1,0
    method: GET
    # Usunięto nagłówek Cookie
    value_template: >
      {{ value.split('Prędkość pompy obiegowej solanki</td>')[1]
              .split('<td class="value">')[1]
              .split('</td>')[0]
              .replace('%', '')
              .replace(',', '.') | float }}
    unit_of_measurement: "%"

  - platform: rest
    name: "Ciśnienie niskie Stiebel Eltron"
    resource: http://192.168.100.126/?s=1,0
    method: GET
    # Usunięto nagłówek Cookie
    value_template: >
      {{ value.split('Strona niskiego ciśnienia, ciśnienie</td>')[1]
              .split('<td class="value">')[1]
              .split('</td>')[0]
              .replace('bar (g)', '')
              .replace(',', '.') | float }}
    unit_of_measurement: "bar"


binary_sensor:
  - platform: rest
    name: "Stiebel Eltron Stan CWU"
    resource: http://192.168.100.126/?s=3,3
    method: GET
    # Usunięto nagłówek Cookie
    value_template: >
      {% set val = value.split('id="aval9" value="')[1].split('"')[0] %}
      {{ val == "ZAL" }}
    device_class: power
    scan_interval: 30


  - platform: rest
    name: "Pompa Stiebel Eltron stan ogrzewania"
    resource: http://192.168.100.126/?s=0
    method: GET
    # Usunięto nagłówek Cookie
    value_template: >
      {% set lines = value.split('\n') %}
      {% for line in lines %}
        {% if 'id="aval10"' in line %}
          {% set val = line.split('value="')[1].split('"')[0] %}
          {{ val == "OGRZEWANIE" }}
        {% endif %}
      {% endfor %}
    device_class: power
    scan_interval: 30


  - platform: rest
    name: "Stiebel Eltron Antylegionella stan"
    resource: http://192.168.100.126/?s=3,3
    method: GET
    value_template: >
      {% if 'id="aval25"' in value %}
        {% set val = value.split('id="aval25" value="')[1].split('"')[0] %}
        {{ val == "ZAL" }}
      {% else %}
        false
      {% endif %}
    device_class: power
    scan_interval: 30